services:
  mini_chat:
    container_name: 'mini_chat'
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh", "-c", "source /app/script.sh"]
    ports:
      - "8090:8000"
    restart: always
    volumes:
      - ./src:/app/src
      - ./alembic/env.py:/app/alembic/env.py
      - ./script.sh:/app/script.sh